on:
  push:
    branches:
      - master
name: Deploy
jobs:
  deploy:
    name: deploy
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - uses: actions/setup-node@master
      with:
        node-version: 16.x
    - run: npm install
    - name: serverless deploy
      uses: serverless/github-action@v3.1
      with:
        args: deploy --stage production
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        HAKATASHI_API_KEY: ${{ secrets.HAKATASHI_API_KEY }}
